class_name EnvironmentDatabase
extends RefCounted

## Static catalog of all 5 environment presets. Built in code so designers
## can iterate without authoring 5 .tres files by hand.

const PRESETS: Dictionary = {
	&"town_day": {
		"display_name": "Town - Day",
		"sun_enabled": true,
		"sun_color": Color(1.0, 0.91, 0.69),
		"sun_energy": 3.5,
		"sun_angle_degrees": Vector2(50, 90),
		"ambient_color": Color(0.55, 0.55, 0.50),
		"ambient_energy": 0.6,
		"sky_horizon_color": Color(0.65, 0.78, 0.95),
		"sky_top_color": Color(0.25, 0.45, 0.85),
		"sky_ground_color": Color(0.4, 0.35, 0.30),
		"sky_energy": 1.0,
		"fog_enabled": false,
		"vfog_enabled": false,
		"bloom_enabled": true,
		"bloom_threshold": 0.4,
		"bloom_intensity": 0.4,
		"ssao_enabled": true,
		"ssao_strength": 0.4,
		"sdfgi_enabled": true,
		"tonemapper_mode": 2,
		"exposure": 1.0,
		"godrays_enabled": false,
	},
	&"town_night": {
		"display_name": "Town - Night",
		"sun_enabled": true,
		"sun_color": Color(0.44, 0.56, 0.75),
		"sun_energy": 1.2,
		"sun_angle_degrees": Vector2(-30, 90),
		"ambient_color": Color(0.10, 0.12, 0.18),
		"ambient_energy": 0.2,
		"sky_horizon_color": Color(0.05, 0.08, 0.15),
		"sky_top_color": Color(0.02, 0.03, 0.08),
		"sky_ground_color": Color(0.0, 0.0, 0.02),
		"sky_energy": 0.3,
		"fog_enabled": true,
		"fog_color": Color(0.10, 0.13, 0.20),
		"fog_density": 0.005,
		"vfog_enabled": true,
		"vfog_density": 0.02,
		"vfog_albedo": Color(0.30, 0.40, 0.60),
		"bloom_enabled": true,
		"bloom_threshold": 0.6,
		"bloom_intensity": 0.6,
		"ssao_enabled": true,
		"ssao_strength": 0.6,
		"sdfgi_enabled": true,
		"tonemapper_mode": 2,
		"exposure": 0.85,
		"godrays_enabled": false,
	},
	&"dungeon_dim": {
		"display_name": "Dungeon - Dim",
		"sun_enabled": false,
		"ambient_color": Color(0.05, 0.07, 0.10),
		"ambient_energy": 0.15,
		"sky_horizon_color": Color.BLACK,
		"sky_top_color": Color.BLACK,
		"sky_ground_color": Color.BLACK,
		"sky_energy": 0.0,
		"fog_enabled": true,
		"fog_color": Color(0.10, 0.12, 0.15),
		"fog_density": 0.02,
		"vfog_enabled": true,
		"vfog_density": 0.08,
		"vfog_albedo": Color(0.25, 0.30, 0.40),
		"bloom_enabled": true,
		"bloom_threshold": 0.5,
		"bloom_intensity": 0.5,
		"ssao_enabled": true,
		"ssao_strength": 0.8,
		"sdfgi_enabled": false,
		"tonemapper_mode": 2,
		"exposure": 1.1,
		"godrays_enabled": false,
	},
	&"boss_arena": {
		"display_name": "Boss Arena",
		"sun_enabled": true,
		"sun_color": Color(1.0, 0.50, 0.31),
		"sun_energy": 5.0,
		"sun_angle_degrees": Vector2(75, 60),
		"ambient_color": Color(0.18, 0.10, 0.10),
		"ambient_energy": 0.3,
		"sky_horizon_color": Color(0.15, 0.05, 0.05),
		"sky_top_color": Color(0.05, 0.02, 0.02),
		"sky_ground_color": Color.BLACK,
		"sky_energy": 0.5,
		"fog_enabled": true,
		"fog_color": Color(0.20, 0.08, 0.08),
		"fog_density": 0.012,
		"vfog_enabled": true,
		"vfog_density": 0.03,
		"vfog_albedo": Color(0.50, 0.20, 0.20),
		"bloom_enabled": true,
		"bloom_threshold": 0.3,
		"bloom_intensity": 0.8,
		"ssao_enabled": true,
		"ssao_strength": 0.7,
		"sdfgi_enabled": false,
		"tonemapper_mode": 2,
		"exposure": 1.15,
		"godrays_enabled": true,
		"godrays_intensity": 0.5,
	},
	&"menu_key": {
		"display_name": "Menu - Key Light",
		"sun_enabled": true,
		"sun_color": Color(0.96, 0.96, 1.0),
		"sun_energy": 4.0,
		"sun_angle_degrees": Vector2(60, 35),
		"ambient_color": Color(0.20, 0.22, 0.30),
		"ambient_energy": 0.4,
		"sky_horizon_color": Color(0.04, 0.05, 0.07),
		"sky_top_color": Color(0.02, 0.03, 0.05),
		"sky_ground_color": Color.BLACK,
		"sky_energy": 0.3,
		"fog_enabled": false,
		"vfog_enabled": false,
		"bloom_enabled": true,
		"bloom_threshold": 0.5,
		"bloom_intensity": 0.5,
		"ssao_enabled": true,
		"ssao_strength": 0.4,
		"sdfgi_enabled": true,
		"tonemapper_mode": 2,
		"exposure": 1.0,
		"godrays_enabled": false,
	},
}


static func get_preset(id: StringName) -> Dictionary:
	return PRESETS.get(id, {})


static func get_all_ids() -> Array:
	return PRESETS.keys()


static func count() -> int:
	return PRESETS.size()
